import os
os.makedirs("Python基础/day01")
os.makedirs("Python基础/day02")
os.makedirs("Python基础/day03")
os.makedirs("Python基础/day04")
os.makedirs("Python基础/day05")

os.makedirs("Python核心特性/day01")
os.makedirs("Python核心特性/day02")
os.makedirs("Python核心特性/day03")
os.makedirs("Python核心特性/day04")
os.makedirs("Python核心特性/day05")
os.makedirs("Python核心特性/day06")
os.makedirs("Python核心特性/day07")
os.makedirs("Python核心特性/day08")
os.makedirs("Python核心特性/day09")
os.makedirs("Python核心特性/day10")

os.makedirs("Python高级阶段/day01")
os.makedirs("Python高级阶段/day02")
os.makedirs("Python高级阶段/day03")
os.makedirs("Python高级阶段/day04")
os.makedirs("Python高级阶段/day05")
os.makedirs("Python高级阶段/day06")
os.makedirs("Python高级阶段/day07")
os.makedirs("Python高级阶段/day08")
os.makedirs("Python高级阶段/day09")
os.makedirs("Python高级阶段/day10")

os.makedirs("Linux_shell编程与HTML初认识/day01")
os.makedirs("Linux_shell编程与HTML初认识/day02")
os.makedirs("Linux_shell编程与HTML初认识/day03")
os.makedirs("Linux_shell编程与HTML初认识/day04")
os.makedirs("Linux_shell编程与HTML初认识/day05")
os.makedirs("Linux_shell编程与HTML初认识/day06")
os.makedirs("Linux_shell编程与HTML初认识/day07")
os.makedirs("Linux_shell编程与HTML初认识/day08")
os.makedirs("Linux_shell编程与HTML初认识/day09")
os.makedirs("Linux_shell编程与HTML初认识/day10")

os.makedirs("HTML_CSS页面布局/day01")
os.makedirs("HTML_CSS页面布局/day02")
os.makedirs("HTML_CSS页面布局/day03")
os.makedirs("HTML_CSS页面布局/day04")
os.makedirs("HTML_CSS页面布局/day05")
os.makedirs("HTML_CSS页面布局/day06")
os.makedirs("HTML_CSS页面布局/day07")
os.makedirs("HTML_CSS页面布局/day08")
os.makedirs("HTML_CSS页面布局/day09")
os.makedirs("HTML_CSS页面布局/day10")

os.makedirs("jquery语_bootstrap_数据库/day01")
os.makedirs("jquery语_bootstrap_数据库/day02")
os.makedirs("jquery语_bootstrap_数据库/day03")
os.makedirs("jquery语_bootstrap_数据库/day04")
os.makedirs("jquery语_bootstrap_数据库/day05")
os.makedirs("jquery语_bootstrap_数据库/day06")
os.makedirs("jquery语_bootstrap_数据库/day07")
os.makedirs("jquery语_bootstrap_数据库/day08")
os.makedirs("jquery语_bootstrap_数据库/day09")
os.makedirs("jquery语_bootstrap_数据库/day10")

os.makedirs("非关系型数据库与django入门/day01")
os.makedirs("非关系型数据库与django入门/day02")
os.makedirs("非关系型数据库与django入门/day03")
os.makedirs("非关系型数据库与django入门/day04")
os.makedirs("非关系型数据库与django入门/day05")
os.makedirs("非关系型数据库与django入门/day06")
os.makedirs("非关系型数据库与django入门/day07")
os.makedirs("非关系型数据库与django入门/day08")
os.makedirs("非关系型数据库与django入门/day09")
os.makedirs("非关系型数据库与django入门/day10")

os.makedirs("Django项目实战/day01")
os.makedirs("Django项目实战/day02")
os.makedirs("Django项目实战/day03")
os.makedirs("Django项目实战/day04")
os.makedirs("Django项目实战/day05")
os.makedirs("Django项目实战/day06")
os.makedirs("Django项目实战/day07")
os.makedirs("Django项目实战/day08")
os.makedirs("Django项目实战/day09")
os.makedirs("Django项目实战/day10")


os.makedirs("初始爬虫与简单应用/day01")
os.makedirs("初始爬虫与简单应用/day02")
os.makedirs("初始爬虫与简单应用/day03")
os.makedirs("初始爬虫与简单应用/day04")
os.makedirs("初始爬虫与简单应用/day05")
os.makedirs("初始爬虫与简单应用/day06")
os.makedirs("初始爬虫与简单应用/day07")
os.makedirs("初始爬虫与简单应用/day08")
os.makedirs("初始爬虫与简单应用/day09")
os.makedirs("初始爬虫与简单应用/day10")

os.makedirs("爬虫实战/day01")
os.makedirs("爬虫实战/day02")
os.makedirs("爬虫实战/day03")
os.makedirs("爬虫实战/day04")
os.makedirs("爬虫实战/day05")
os.makedirs("爬虫实战/day06")
os.makedirs("爬虫实战/day07")
os.makedirs("爬虫实战/day08")
os.makedirs("爬虫实战/day09")
os.makedirs("爬虫实战/day10")

os.makedirs("数据分析/day01")
os.makedirs("数据分析/day02")
os.makedirs("数据分析/day03")
os.makedirs("数据分析/day04")
os.makedirs("数据分析/day05")
os.makedirs("数据分析/day06")
os.makedirs("数据分析/day07")
os.makedirs("数据分析/day08")
os.makedirs("数据分析/day09")
os.makedirs("数据分析/day10")

os.makedirs("机器学习/day01")
os.makedirs("机器学习/day02")
os.makedirs("机器学习/day03")
os.makedirs("机器学习/day04")
os.makedirs("机器学习/day05")
os.makedirs("机器学习/day06")
os.makedirs("机器学习/day07")
os.makedirs("机器学习/day08")
os.makedirs("机器学习/day09")
os.makedirs("机器学习/day10")

